#!/bin/bash
pushd `dirname $0` > /dev/null
SCRIPT_PATH=`pwd`
popd > /dev/null
PUPPET_PATH="${SCRIPT_PATH}/../puppet"
MODULES_PATH="${PUPPET_PATH}/modules"
HIERA_CONFIG="${SCRIPT_PATH}/../hiera/hiera.yaml"
HIERA_DATADIR="${SCRIPT_PATH}/../hiera/datadir/"
ENV=production

if ! [ -L /usr/bin/ruby ]; then
  apt-get install -y -f ruby2.0
fi

if ! [ -e /usr/bin/bundle ]; then
  apt-get install -y -f bundler
fi

if ! bundle check 1>&2 >/dev/null ; then
  bundle install
fi

sudo -E puppet apply --verbose --hiera_config=$HIERA_CONFIG --modulepath=$MODULES_PATH $PUPPET_PATH/manifests/default.pp --environment=$ENV --show_diff $@




